languageCode = "pl-pl"
title = "Zielony Buszmen"
baseurl = "https://zielonybuszmen.github.io/"
theme = "beautifulhugo"
paginate = "10"
pygmentsUseClasses = true
pygmentCodeFences = true

tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["blog", "themes", "disqus", "minimal", "responsive"]

[author]
    name = "halogenica"
    homepage = "http://halogenica.net"

# If Porting existing theme
[original]
    author =  "dattali"
    homepage = "http://deanattali.com/beautiful-jekyll/"
    repo = "https://github.com/daattali/beautiful-jekyll"


[Author]
    name = "Zielony Buszmen"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"
    homepage = "http://halogenica.net"


[Params]
    subtitle = "Mocno techniczny blog programistyczny" # Subtitle of your site
    description = " Mocno techniczny blog programistyczny" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
     logo = "img/avatar-icon.png"
      favicon = "img/favicon.ico"
    dateFormat = "2 January 2006"
      commit = false
      rss = true
    comments = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget


[menu]
    [[menu.main]]
    identifier = "news"
    name       = "Main()" # zrobić, aby wyglądało jak main() z c#
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "projekty"
    name       = "Zrealizowane projekty"
    url        = "/categories/projekty/"
    weight     = 1

    [[menu.main]]
    identifier = "o-mnie"
    name       = "O mnie"
    url        = "/o-mnie/"
    weight     = 2

    [[menu.main]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/ZielonyBuszmen"
    weight     = 3