baseurl = "https://zielonybuszmen.github.io/"
DefaultContentLanguage = "pl"
languageCode = "pl-pl"
title = "Zielony Buszmen"
theme = "beautifulhugo"
paginate = "50"
pygmentsUseClasses = true
pygmentCodeFences = true
metaDataFormat = "yaml"
disqusShortname = "zielonybuszmen-github-io"


# If Porting existing theme
[original]
    author =  "dattali"
    homepage = "http://deanattali.com/beautiful-jekyll/"
    repo = "https://github.com/daattali/beautiful-jekyll"

[[Params.bigimg]]
    # src = "img/sphere.jpg"
    src = "img/tlo2.png"
    #desc = "Triangle"

[Author]
    name = "Zielony Buszmen"
    bio = "Opis bio"
    avatar = "img/avatar.png"
    website = "https://zielonybuszmen.github.io/"
    github = "ZielonyBuszmen"

[Params]
    subtitle = "Mocno techniczny blog programistyczny" # Subtitle of your site
    description = " Mocno techniczny blog programistyczny" # Description of your site
    post_navigation = true
    # logo = "img/avatar-green.png"
      favicon = "img/avatar-green.png"
    dateFormat = "2006-01-02"
      commit = false
      rss = true
    comments = true
    custom_css = ["/prism-highlighter/darcula.css", "/styles/my.css"]
    custom_js = ["/prism-highlighter/prism.js", "/js/my.css"] # custom js nie działa, kod w footer.html
    gcse = '007478084746714163272:uz5nuajlf-i'


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget


[menu]
    [[menu.main]]
    identifier = "projekty"
    name       = "Projekty"
    url        = "https://zielonybuszmen.github.io/MyProjects/"
    weight     = 1

    [[menu.main]]
    identifier = "o-mnie"
    name       = "O mnie"
    url        = "/o-mnie/"
    weight     = 2


    [[menu.main]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/ZielonyBuszmen"
    weight     = 4

    [[menu.main]]
        identifier = "menu"
        pre = "<i class='fa fa-heart'></i> - tutaj może być ikonka"
        name = "Menu"
        weight = 5

    [[menu.main]]
        parent = "menu"
        name = "Kategorie"
        url = "categories"
        weight = 1

    [[menu.main]]
        parent = "menu"
        name = "Tagi"
        url = "tags"
        weight = 2