languageCode = "pl-pl"
title = "Zielony Buszmen"
baseurl = "https://zielonybuszmen.github.io/"
theme = "mainroad"
paginate = "10"


[Author]
    name = "Zielony Buszmen"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"


[Params]
    subtitle = "Mocno techniczny blog programistyczny" # Subtitle of your site
    description = " John Doe's Personal blog about everything" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget


[menu]
    [[menu.main]]
    identifier = "news"
    name       = "Main()" # zrobić, aby wyglądało jak main() z c#
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "projekty"
    name       = "Zrealizowane projekty"
    url        = "/projekty/"
    weight     = 1

    [[menu.main]]
    identifier = "o-mnie"
    name       = "O mnie"
    url        = "/o-mnie/"
    weight     = 2

    [[menu.main]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/ZielonyBuszmen"
    weight     = 3